"""添加avatar_hash字段，用于缓存MD5

Revision ID: 60db49e3ef08
Revises: aa4b4bca749b
Create Date: 2016-03-08 06:07:00.638171

"""

# revision identifiers, used by Alembic.
revision = '60db49e3ef08'
down_revision = 'aa4b4bca749b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
