"""修复Post模型中body_html字段

Revision ID: 72a9907f0386
Revises: 303ab3f07cb6
Create Date: 2016-03-10 17:32:17.362702

"""

# revision identifiers, used by Alembic.
revision = '72a9907f0386'
down_revision = '303ab3f07cb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
