"""评论模型添加disabled字段，用于标记不当评论

Revision ID: 7699d65953bc
Revises: bfe84cc95e1d
Create Date: 2016-03-15 03:12:29.041873

"""

# revision identifiers, used by Alembic.
revision = '7699d65953bc'
down_revision = 'bfe84cc95e1d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    ### end Alembic commands ###
