"""role模型添加default, permissions字段，和生成角色的静态方法

Revision ID: dc405960293f
Revises: 3f21b4a95297
Create Date: 2016-03-07 15:08:59.182761

"""

# revision identifiers, used by Alembic.
revision = 'dc405960293f'
down_revision = '3f21b4a95297'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
