"""添加关注关联表，用户模型中添加关注者和被关注者字段，添加验证关注关系函数

Revision ID: fe928ee5c2d6
Revises: 72a9907f0386
Create Date: 2016-03-13 14:50:34.961474

"""

# revision identifiers, used by Alembic.
revision = 'fe928ee5c2d6'
down_revision = '72a9907f0386'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    ### end Alembic commands ###
